[pytest]
markers =
    cls: marker for TCs using class session scope
    session: marker for TCs using session scope
    codegen: marker for TCs using codegen
    locator: marker for TCs using locator
    builtinlocators: marker for TCs using builtin locators
    browser: marker for TCs using browser

addopts = --html=output_files/latest.html --self-contained-html --browser=firefox --headed 
