[pytest]
markers =
    mockdata: marker for mockdata TCs
    mock_request: marker for mocking API request testcases
    mock_response: marker for mocking API response
    login: marker for orageHRM website related test


# add --tracing on in addopts or directly on pytest cli prompt to enable tracing for all tests.
# default its value is off. You can also set it to on, retain-on-failure.
# It will create test-results/testfolder/trace.zip
# which can be opened in Playwright trace viewer to analyze the test execution step by step.
# To open trace file user playwright show-trace test-results/testfolder/trace.zip
addopts = --html=output_files/latest.html --self-contained-html --browser=firefox --headed
