[pytest]
python_files = check_*.py test_*.py
python_classes = Check* Test*
python_functions = check_* test_*
markers = parameter: tests that use parameterization for login
          storage: tests related to storage functionality
