[pytest]
markers =
    cls: marker for TCs using class session scope
    session: marker for TCs using session scope
    codegen: marker for TCs using codegen
    locator: marker for TCs using locator
    builtinlocators: marker for TCs using builtin locators
    browser: marker for TCs using browser
    jsalert: marker for TCs using jsalert
    iframe: marker for TCs using iframe
    tracing: marker for TCs using tracing
    dropdown: marker for TCs using dropdown
    tables: marker for TCs using table
    stables: marker for TCs using sortable table
    form: marker for TCs using form

# add --tracing on in addopts or directly on pytest cli prompt to enable tracing for all tests.
# default its value is off. You can also set it to on, retain-on-failure.
# It will create test-results/testfolder/trace.zip
# which can be opened in Playwright trace viewer to analyze the test execution step by step.
# To open trace file user playwright show-trace test-results/testfolder/trace.zip
addopts = --html=output_files/latest.html --self-contained-html --browser=firefox --headed
