[pytest]
python_files = check_*.py test_*.py
python_classes = Check* Test*
python_functions = check_* test_*

markers =
    api: mark a test as an API test
    api_get: mark a test as an API GET test
    api_post: mark a test as an API POST test
    api_patch: mark a test as an API PATCH test
    api_put: mark a test as an API PUT test
    api_delete: mark a test as an API DELETE test